print ("===================CAFE===================")
print ("==========MASUKKAN JUMLAH HARGA==========")
a= int (print ("CAPPUCINO \tDISKON 50% \tRP 25.000 \t:3"))
b= int (print ("VANILLA LATTE \tDISKON 65% \tRP 22.000 \t:4"))
c= int (print("AMERICANO \tDISKON 35% \tRP 30.000 \t:2"))